name: mi_card
description: Mi Card app

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^0.2.0
  flutter_hooks: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: BerkshireSwash
      fonts:
      - asset: fonts/BerkshireSwash-Regular.ttf

    - family: Acme
      fonts:
        - asset: fonts/Acme-Regular.ttf


